### ISSUE TITLE
Fails to load the Jinja template

### ISSUE THREAD

**Issue by mandx** [pradyunsg/Sublime-Rainbow-Theme#2]
```
Traceback (most recent call last):
  File "rainbow_lib.theme_manager in /home/mandx/.config/sublime-text-3/Installed Packages/Theme - Rainbow.sublime-package", line 65, in get_rendered_theme_parts
  File "rainbow_lib.cache in /home/mandx/.config/sublime-text-3/Installed Packages/Theme - Rainbow.sublime-package", line 101, in get
KeyError: "No entries for key: 'theme-1b2b34-soda-dark'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rainbow_lib.adapter in /home/mandx/.config/sublime-text-3/Installed Packages/Theme - Rainbow.sublime-package", line 65, in run
  File "rainbow_lib.theme_manager in /home/mandx/.config/sublime-text-3/Installed Packages/Theme - Rainbow.sublime-package", line 71, in get_rendered_theme_parts
  File "rainbow_lib.compiler in /home/mandx/.config/sublime-text-3/Installed Packages/Theme - Rainbow.sublime-package", line 24, in render_part
  File "/home/mandx/.config/sublime-text-3/Packages/python-jinja2/all/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/mandx/.config/sublime-text-3/Packages/python-jinja2/all/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/home/mandx/.config/sublime-text-3/Packages/python-jinja2/all/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: theme.jinja2
```

Please note I installed this from Package Control, maybe installing this directly from Git may work, since ST packages are just a compressed archive. Maybe the error has to to with Jinja trying to load a template from the actual filesystem while they reside inside the archive?

**Comment by pradyunsg** [comment]
Thank you for filing this issue.

> Maybe the error has to to with Jinja trying to load a template from the actual filesystem while they reside inside the archive?

Indeed. I'll push a fix.
