### ISSUE TITLE
Theme not showing up, when shows up, doesn't work.

### ISSUE THREAD

**Issue by mikerockett** [pradyunsg/Sublime-Rainbow-Theme#4]
Theme list is not showing this theme, even after satisfying dependencies after git clone. No errors, either...

Any ideas?

**Comment by pradyunsg** [comment]
Thank you for filing this issue. Could you please add a bit more information about what theme list you are referring to; to help narrow down the possible causes?

AFAIK, simply activating the theme once, by setting the theme key in Preferences should suffice.

**Comment by mikerockett** [comment]
When the package is installed (either via Package Control or Git), the Themr package does not list the theme in the drop down list (Ctrl+Shift+P > Themr: List Themes). Other themes do show up in the list, so I'm not sure what's preventing this specific one from showing up.

**Comment by pradyunsg** [comment]
Ooh, that is because the Themr looks for .sublime-theme files. And this package does not generate any until it is activated (by manually setting theme). For now, please manually activate the theme, by setting theme key in Preferences... I'll push a fix for this when I'm near a PC.

**Comment by mikerockett** [comment]
Ah, that makes sense. Thanks. :+1:

**Comment by mikerockett** [comment]
I'm afraid this doesn't work at all - Sublime picks up a problem with the theme and resets to default...

**Comment by pradyunsg** [comment]
Hmm.. I'll try it on one of my friend's clean machine... :sweat_smile:

**Comment by mikerockett** [comment]
Thanks - I'm running ST3 (3114) if that means anything. :smile:

**Comment by pradyunsg** [comment]
Cool. I'll get the same then...

**Comment by pradyunsg** [comment]
Could you open a new session of Sublime Text and copy-paste what you see in the console.

**Comment by mikerockett** [comment]
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\main.py", line 8, in <module>
    from .rainbow_lib import RainbowThemeAdapter
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\__init__.py", line 1, in <module>
    from .adapter import RainbowThemeAdapter
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\adapter.py", line 4, in <module>
    from . import core
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\core\__init__.py", line 4, in <module>
    from . import utils
ImportError: cannot import name utils
```

I get that from a fresh git clone.

**Comment by mikerockett** [comment]
Restarting gives me this:

```
...
File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\compiler.py", line 4, in <module>
    import jinja2
ImportError: No module named 'jinja2'
```

And then it resets to the default theme.

**Comment by mikerockett** [comment]
Out of curiosity, what ST3 build did you develop with? I only just realised that 3114 is the latest stable.

**Comment by pradyunsg** [comment]
I checked. It's 3114 too.

It's working on this new machine. I added the dependencies.json. Did you try it with fd65083?

**Comment by pradyunsg** [comment]
No wait!

**Comment by pradyunsg** [comment]
I meant 9763a87

**Comment by mikerockett** [comment]
```
jinja2.exceptions.TemplateNotFound: widget-settings.jinja2
```

After restart:

```
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib.core.utils
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib.core.logging
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib.core.fsi
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib.core
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib.colour
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib.context_manager
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib.preferences_manager
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib.cache
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib.compiler
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib.theme_manager
[RAINBOW] Did not reload: Theme - Rainbow.rainbow_lib.adapter
reloading plugin Sublime-Rainbow-Theme.main
reloading settings Packages/User/phpfmt.sublime-settings
reloading plugin Sublime-Rainbow-Theme.reloader_command
```

**Comment by mikerockett** [comment]
Hold on, I'm way to used to Package Control - should I have cloned into `User`? Just asking because that template file does exist...

**Comment by pradyunsg** [comment]
Thanks for sticking this out with me.

Just uninstall, restart, install via package control, restart and copy-paste the console log

**Comment by pradyunsg** [comment]
> Hold on, I'm way to used to Package Control - should I have cloned into User? Just asking because that template file does exist...

Well, last comment. :sweat_smile:

**Comment by mikerockett** [comment]
Sure thing. :+1:

That doesn't seem to work - not sure if Package Control is caching releases or something, because it doesn't pull in jinja, and Package Control claims all dependencies are met.

**Comment by mikerockett** [comment]
Also, at some point during my re-attempts, it gave a similar `TemplateNotFound` error, but for `widget-scheme` instead.

**Comment by mikerockett** [comment]
Also tested on a fresh ST3114 portable - same error as previous comment, and the default theme doesn't kick in after that.

**Comment by pradyunsg** [comment]
I'm well, it's working on my end... And this is a fresh install. Could you
please check if the current HEAD fixes it?

**Comment by mikerockett** [comment]
HEAD refers to current master - I see no changes there?

**Comment by mikerockett** [comment]
Whats even more strange is that the template error keeps changing. Now it's this:

```
jinja2.exceptions.TemplateNotFound: theme.jinja2
```

**Comment by pradyunsg** [comment]
Yeah. I meant the current master.

I just wanna make sure. 😆

**Comment by mikerockett** [comment]
Hehe - yeah, I'm up to date.

**Comment by mikerockett** [comment]
I wonder if this is not a filesystem issue... Unfortunately, console isn't showing me absolute paths for requested jinja files, and I'm not a Python coder, so not really able to check how it's looking for those files. Perhaps it's a jinja problem?

**Comment by pradyunsg** [comment]
I am working with 3114. What's your OS? The required jinja files are in the
package, in the templates directory.

**Comment by mikerockett** [comment]
I'm on Win 10 64-bit...

Here's a full trace:

```
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\theme_manager.py", line 65, in get_rendered_theme_parts
    val = self.cache.get(cache_key)
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\cache.py", line 101, in get
    raise KeyError("No entries for key: {!r}".format(key))
KeyError: "No entries for key: 'widget-settings-282c34-soda-light'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 333, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\main.py", line 49, in on_activated_async
    rta.run('tab change')
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\adapter.py", line 65, in run
    context, scheme_colours, variant
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\theme_manager.py", line 71, in get_rendered_theme_parts
    val = self.compiler.render_part(thing, context, helpers)
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\compiler.py", line 24, in render_part
    template = self._jinja_env.get_template(template_name)
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: widget-settings.jinja2
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\theme_manager.py", line 65, in get_rendered_theme_parts
    val = self.cache.get(cache_key)
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\cache.py", line 101, in get
    raise KeyError("No entries for key: {!r}".format(key))
KeyError: "No entries for key: 'widget-settings-282c34-soda-light'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\adapter.py", line 65, in run
    context, scheme_colours, variant
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\theme_manager.py", line 71, in get_rendered_theme_parts
    val = self.compiler.render_part(thing, context, helpers)
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\compiler.py", line 24, in render_part
    template = self._jinja_env.get_template(template_name)
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: widget-settings.jinja2
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\theme_manager.py", line 65, in get_rendered_theme_parts
    val = self.cache.get(cache_key)
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\cache.py", line 101, in get
    raise KeyError("No entries for key: {!r}".format(key))
KeyError: "No entries for key: 'widget-settings-282c34-soda-light'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\adapter.py", line 65, in run
    context, scheme_colours, variant
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\theme_manager.py", line 71, in get_rendered_theme_parts
    val = self.compiler.render_part(thing, context, helpers)
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\compiler.py", line 24, in render_part
    template = self._jinja_env.get_template(template_name)
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: widget-settings.jinja2
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\theme_manager.py", line 65, in get_rendered_theme_parts
    val = self.cache.get(cache_key)
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\cache.py", line 101, in get
    raise KeyError("No entries for key: {!r}".format(key))
KeyError: "No entries for key: 'widget-settings-282c34-soda-light'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 333, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\main.py", line 49, in on_activated_async
    rta.run('tab change')
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\adapter.py", line 65, in run
    context, scheme_colours, variant
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\theme_manager.py", line 71, in get_rendered_theme_parts
    val = self.compiler.render_part(thing, context, helpers)
  File "C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\Sublime-Rainbow-Theme\rainbow_lib\compiler.py", line 24, in render_part
    template = self._jinja_env.get_template(template_name)
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "C:\Users\xx\AppData\Roaming\SUBLIM~1\Packages\PYTHON~1\all\jinja2\loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: widget-settings.jinja2
```

**Comment by pradyunsg** [comment]
Hmm... I'm out of ideas.. And it's a little late. Do you mind if I ping you
tomorrow?

**Comment by mikerockett** [comment]
Sure thing - I need to head to a meeting in 20 anyway. :+1:

**Comment by mikerockett** [comment]
You won't believe me when I tell you this, but it's because the theme directory name is incorrect. It needs to be `Theme - Rainbow`, which it won't be when done via Git. Please add this to the readme. 👍

**Comment by mikerockett** [comment]
That said, the `Dark` variant doesn't work still...

**Comment by pradyunsg** [comment]
> You won't believe me when I tell you this, but it's because the theme directory name is incorrect. It needs to be `Theme - Rainbow`, which it won't be when done via Git. Please add this to the readme. :+1:

Huh. I didn't think of that.

> That said, the `Dark` variant doesn't work still...

It should work now. I fixed the Themr issues.

**Comment by pradyunsg** [comment]
Thanks a lot @mikerockett for filing this issue and coming up with the solution. :smile: 

Liking the theme? :innocent:

**Comment by mikerockett** [comment]
Hehe, you're most welcome. I'll give it a try now.

**Comment by mikerockett** [comment]
Works like magic! 👍
